In [1]:
%config Completer.use_jedi=False
import torch
from torch import nn
import numpy as np
from torch import optim
from torch.autograd import Variable
import torch.nn.functional as F

In [2]:
torch.cuda.is_available()

False

In [3]:
class NeuralNet(nn.Module):
    
    def __init__(self):
        super(NeuralNet,self).__init__()
        self.fc1=nn.Linear(1,10)
        self.fc2=nn.Linear(10,1)

    def forward(self,x):
        x=F.relu(self.fc1(x))
        out=self.fc2(x)
        return out

In [4]:
# train=torch.rand([25,10])
train=np.array(range(1,10001))*10
mean=np.mean(train)
std=np.std(train)
train=train - mean
train=train/std
train=torch.from_numpy(train)
train=train.view(-1,1)
train=train.type('torch.FloatTensor')

In [5]:
target=train*23


train, target = Variable(train), Variable(target)

In [6]:
x = torch.unsqueeze(torch.linspace(-1, 1, 100), dim=1)  # x data (tensor), shape=(100, 1)
y = x.pow(2) + 0.2*torch.rand(x.size())                 # noisy y data (tensor), shape=(100, 1)

# torch can only train on Variable, so convert them to Variable
train, target = Variable(x), Variable(y)

In [7]:
net=NeuralNet()

In [8]:
# y.backward(torch.rand(y.shape))
# target=torch.rand(y.shape)

In [9]:
criterion=nn.MSELoss()

In [10]:
optimizer=optim.SGD(net.parameters(),lr=0.2)

In [11]:
print('net.fc1.weight',net.fc1.weight)
print('net.fc1.weight.grad',net.fc1.weight.grad)

print('net.fc1.bias',net.fc1.bias)
print('net.fc1.bias.grad',net.fc1.bias.grad)

net.fc1.weight Parameter containing:
tensor([[-0.4823],
        [ 0.1612],
        [ 0.0167],
        [-0.4264],
        [-0.5763],
        [-0.2684],
        [ 0.7810],
        [ 0.6285],
        [-0.4488],
        [ 0.8122]], requires_grad=True)
net.fc1.weight.grad None
net.fc1.bias Parameter containing:
tensor([-0.4486,  0.3782,  0.7233,  0.6963,  0.1526,  0.1164,  0.6883, -0.6853,
         0.9756,  0.3303], requires_grad=True)
net.fc1.bias.grad None


In [12]:
for _ in range(1000):
    optimizer.zero_grad()
#     print('\n\n Zero the gradiants')
#     print('net.fc1.weight',net.fc1.weight)
#     print('net.fc1.weight.grad',net.fc1.weight.grad)

#     print('net.fc1.bias',net.fc1.bias)
#     print('net.fc1.bias.grad',net.fc1.bias.grad)
    y=net.forward(train)
    loss=criterion(target,y)
    print('\nLoss',loss)
    loss.backward()
    optimizer.step()
#     print('\n\n Update the weights')
#     print('net.fc1.weight',net.fc1.weight)
#     print('net.fc1.weight.grad',net.fc1.weight.grad)

#     print('net.fc1.bias',net.fc1.bias)
#     print('net.fc1.bias.grad',net.fc1.bias.grad)


Loss tensor(0.1621, grad_fn=<MseLossBackward>)

Loss tensor(0.1198, grad_fn=<MseLossBackward>)

Loss tensor(0.1051, grad_fn=<MseLossBackward>)

Loss tensor(0.0978, grad_fn=<MseLossBackward>)

Loss tensor(0.0944, grad_fn=<MseLossBackward>)

Loss tensor(0.0924, grad_fn=<MseLossBackward>)

Loss tensor(0.0908, grad_fn=<MseLossBackward>)

Loss tensor(0.0895, grad_fn=<MseLossBackward>)

Loss tensor(0.0882, grad_fn=<MseLossBackward>)

Loss tensor(0.0869, grad_fn=<MseLossBackward>)

Loss tensor(0.0855, grad_fn=<MseLossBackward>)

Loss tensor(0.0842, grad_fn=<MseLossBackward>)

Loss tensor(0.0829, grad_fn=<MseLossBackward>)

Loss tensor(0.0815, grad_fn=<MseLossBackward>)

Loss tensor(0.0802, grad_fn=<MseLossBackward>)

Loss tensor(0.0788, grad_fn=<MseLossBackward>)

Loss tensor(0.0774, grad_fn=<MseLossBackward>)

Loss tensor(0.0760, grad_fn=<MseLossBackward>)

Loss tensor(0.0746, grad_fn=<MseLossBackward>)

Loss tensor(0.0731, grad_fn=<MseLossBackward>)

Loss tensor(0.0717, grad_fn=<MseLossBac


Loss tensor(0.0070, grad_fn=<MseLossBackward>)

Loss tensor(0.0070, grad_fn=<MseLossBackward>)

Loss tensor(0.0070, grad_fn=<MseLossBackward>)

Loss tensor(0.0070, grad_fn=<MseLossBackward>)

Loss tensor(0.0069, grad_fn=<MseLossBackward>)

Loss tensor(0.0069, grad_fn=<MseLossBackward>)

Loss tensor(0.0069, grad_fn=<MseLossBackward>)

Loss tensor(0.0069, grad_fn=<MseLossBackward>)

Loss tensor(0.0069, grad_fn=<MseLossBackward>)

Loss tensor(0.0069, grad_fn=<MseLossBackward>)

Loss tensor(0.0069, grad_fn=<MseLossBackward>)

Loss tensor(0.0068, grad_fn=<MseLossBackward>)

Loss tensor(0.0068, grad_fn=<MseLossBackward>)

Loss tensor(0.0068, grad_fn=<MseLossBackward>)

Loss tensor(0.0068, grad_fn=<MseLossBackward>)

Loss tensor(0.0068, grad_fn=<MseLossBackward>)

Loss tensor(0.0068, grad_fn=<MseLossBackward>)

Loss tensor(0.0068, grad_fn=<MseLossBackward>)

Loss tensor(0.0068, grad_fn=<MseLossBackward>)

Loss tensor(0.0067, grad_fn=<MseLossBackward>)

Loss tensor(0.0067, grad_fn=<MseLossBac


Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBackward>)

Loss tensor(0.0050, grad_fn=<MseLossBac

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBackward>)

Loss tensor(0.0045, grad_fn=<MseLossBack


Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBackward>)

Loss tensor(0.0042, grad_fn=<MseLossBac

In [13]:
net.fc2.weight

Parameter containing:
tensor([[-0.0832,  0.0109, -0.2109, -0.0070,  1.1116,  0.2678,  0.7639,  0.3110,
         -0.1091,  0.5817]], requires_grad=True)

In [14]:
net.fc1.weight

Parameter containing:
tensor([[-0.4656],
        [ 0.1404],
        [ 0.0328],
        [-0.4419],
        [-1.1626],
        [-0.3274],
        [ 1.1692],
        [ 0.6285],
        [-0.4531],
        [ 1.0427]], requires_grad=True)

In [ ]:
waht=torch.from_numpy(np.array([[1.0]]))
waht=waht.type('torch.FloatTensor')
net(waht)