In [1]:
%config Completer.use_jedi=False
import torch
from torch import nn
import numpy as np
from torch import optim
from torch.autograd import Variable
import torch.nn.functional as F

In [2]:
torch.cuda.is_available()

False

In [3]:
class NeuralNet(nn.Module):
    
    def __init__(self):
        super(NeuralNet,self).__init__()
        self.fc1=nn.Linear(1,10)
        self.fc2=nn.Linear(10,1)

    def forward(self,x):
        x=F.relu(self.fc1(x))
        out=self.fc2(x)
        return out

In [4]:
# train=torch.rand([25,10])
train=np.array(range(1,10001))*10
mean=np.mean(train)
std=np.std(train)
train=train - mean
train=train/std
train=torch.from_numpy(train)
train=train.view(-1,1)
train=train.type('torch.FloatTensor')

In [5]:
target=train*23


train, target = Variable(train), Variable(target)

In [6]:
# x = torch.unsqueeze(torch.linspace(-1, 1, 100), dim=1)  # x data (tensor), shape=(100, 1)
# y = x.pow(2) + 0.2*torch.rand(x.size())                 # noisy y data (tensor), shape=(100, 1)

# # torch can only train on Variable, so convert them to Variable
# train, target = Variable(x), Variable(y)

In [7]:
net=NeuralNet()

In [8]:
# y.backward(torch.rand(y.shape))
# target=torch.rand(y.shape)

In [9]:
criterion=nn.MSELoss()

In [10]:
optimizer=optim.SGD(net.parameters(), lr=0.001,momentum=0.9)

In [11]:
print('net.fc1.weight',net.fc1.weight)
print('net.fc1.weight.grad',net.fc1.weight.grad)

print('net.fc1.bias',net.fc1.bias)
print('net.fc1.bias.grad',net.fc1.bias.grad)

net.fc1.weight Parameter containing:
tensor([[-0.3873],
        [-0.4889],
        [-0.8194],
        [-0.4255],
        [ 0.6704],
        [-0.2625],
        [-0.0651],
        [ 0.4747],
        [-0.9663],
        [-0.2721]], requires_grad=True)
net.fc1.weight.grad None
net.fc1.bias Parameter containing:
tensor([ 0.7344,  0.6617, -0.5081,  0.3941,  0.9737,  0.5204, -0.8193,  0.0093,
         0.8614, -0.4514], requires_grad=True)
net.fc1.bias.grad None


In [12]:
for _ in range(1000):
    optimizer.zero_grad()
#     print('\n\n Zero the gradiants')
#     print('net.fc1.weight',net.fc1.weight)
#     print('net.fc1.weight.grad',net.fc1.weight.grad)

#     print('net.fc1.bias',net.fc1.bias)
#     print('net.fc1.bias.grad',net.fc1.bias.grad)
    y=net.forward(train)
    loss=criterion(target,y)
    print('\nLoss',loss)
    loss.backward()
    optimizer.step()
#     print('\n\n Update the weights')
#     print('net.fc1.weight',net.fc1.weight)
#     print('net.fc1.weight.grad',net.fc1.weight.grad)

#     print('net.fc1.bias',net.fc1.bias)
#     print('net.fc1.bias.grad',net.fc1.bias.grad)


Loss tensor(515.7499, grad_fn=<MseLossBackward>)

Loss tensor(511.8028, grad_fn=<MseLossBackward>)

Loss tensor(504.2959, grad_fn=<MseLossBackward>)

Loss tensor(493.5223, grad_fn=<MseLossBackward>)

Loss tensor(479.6258, grad_fn=<MseLossBackward>)

Loss tensor(462.5852, grad_fn=<MseLossBackward>)

Loss tensor(442.1938, grad_fn=<MseLossBackward>)

Loss tensor(418.1103, grad_fn=<MseLossBackward>)

Loss tensor(389.9629, grad_fn=<MseLossBackward>)

Loss tensor(357.5015, grad_fn=<MseLossBackward>)

Loss tensor(320.7836, grad_fn=<MseLossBackward>)

Loss tensor(280.3752, grad_fn=<MseLossBackward>)

Loss tensor(237.5096, grad_fn=<MseLossBackward>)

Loss tensor(194.1150, grad_fn=<MseLossBackward>)

Loss tensor(152.6541, grad_fn=<MseLossBackward>)

Loss tensor(115.8172, grad_fn=<MseLossBackward>)

Loss tensor(85.3774, grad_fn=<MseLossBackward>)

Loss tensor(62.0440, grad_fn=<MseLossBackward>)

Loss tensor(45.8065, grad_fn=<MseLossBackward>)

Loss tensor(36.6685, grad_fn=<MseLossBackward>)

Los


Loss tensor(0.8568, grad_fn=<MseLossBackward>)

Loss tensor(0.8455, grad_fn=<MseLossBackward>)

Loss tensor(0.8344, grad_fn=<MseLossBackward>)

Loss tensor(0.8233, grad_fn=<MseLossBackward>)

Loss tensor(0.8124, grad_fn=<MseLossBackward>)

Loss tensor(0.8017, grad_fn=<MseLossBackward>)

Loss tensor(0.7910, grad_fn=<MseLossBackward>)

Loss tensor(0.7805, grad_fn=<MseLossBackward>)

Loss tensor(0.7701, grad_fn=<MseLossBackward>)

Loss tensor(0.7598, grad_fn=<MseLossBackward>)

Loss tensor(0.7496, grad_fn=<MseLossBackward>)

Loss tensor(0.7395, grad_fn=<MseLossBackward>)

Loss tensor(0.7296, grad_fn=<MseLossBackward>)

Loss tensor(0.7197, grad_fn=<MseLossBackward>)

Loss tensor(0.7100, grad_fn=<MseLossBackward>)

Loss tensor(0.7004, grad_fn=<MseLossBackward>)

Loss tensor(0.6909, grad_fn=<MseLossBackward>)

Loss tensor(0.6815, grad_fn=<MseLossBackward>)

Loss tensor(0.6722, grad_fn=<MseLossBackward>)

Loss tensor(0.6631, grad_fn=<MseLossBackward>)

Loss tensor(0.6540, grad_fn=<MseLossBac


Loss tensor(0.0742, grad_fn=<MseLossBackward>)

Loss tensor(0.0734, grad_fn=<MseLossBackward>)

Loss tensor(0.0726, grad_fn=<MseLossBackward>)

Loss tensor(0.0717, grad_fn=<MseLossBackward>)

Loss tensor(0.0710, grad_fn=<MseLossBackward>)

Loss tensor(0.0702, grad_fn=<MseLossBackward>)

Loss tensor(0.0694, grad_fn=<MseLossBackward>)

Loss tensor(0.0686, grad_fn=<MseLossBackward>)

Loss tensor(0.0679, grad_fn=<MseLossBackward>)

Loss tensor(0.0672, grad_fn=<MseLossBackward>)

Loss tensor(0.0665, grad_fn=<MseLossBackward>)

Loss tensor(0.0658, grad_fn=<MseLossBackward>)

Loss tensor(0.0651, grad_fn=<MseLossBackward>)

Loss tensor(0.0644, grad_fn=<MseLossBackward>)

Loss tensor(0.0637, grad_fn=<MseLossBackward>)

Loss tensor(0.0630, grad_fn=<MseLossBackward>)

Loss tensor(0.0624, grad_fn=<MseLossBackward>)

Loss tensor(0.0618, grad_fn=<MseLossBackward>)

Loss tensor(0.0611, grad_fn=<MseLossBackward>)

Loss tensor(0.0605, grad_fn=<MseLossBackward>)

Loss tensor(0.0599, grad_fn=<MseLossBac

Loss tensor(0.0222, grad_fn=<MseLossBackward>)

Loss tensor(0.0222, grad_fn=<MseLossBackward>)

Loss tensor(0.0221, grad_fn=<MseLossBackward>)

Loss tensor(0.0221, grad_fn=<MseLossBackward>)

Loss tensor(0.0220, grad_fn=<MseLossBackward>)

Loss tensor(0.0220, grad_fn=<MseLossBackward>)

Loss tensor(0.0220, grad_fn=<MseLossBackward>)

Loss tensor(0.0219, grad_fn=<MseLossBackward>)

Loss tensor(0.0219, grad_fn=<MseLossBackward>)

Loss tensor(0.0218, grad_fn=<MseLossBackward>)

Loss tensor(0.0218, grad_fn=<MseLossBackward>)

Loss tensor(0.0217, grad_fn=<MseLossBackward>)

Loss tensor(0.0217, grad_fn=<MseLossBackward>)

Loss tensor(0.0216, grad_fn=<MseLossBackward>)

Loss tensor(0.0216, grad_fn=<MseLossBackward>)

Loss tensor(0.0215, grad_fn=<MseLossBackward>)

Loss tensor(0.0215, grad_fn=<MseLossBackward>)

Loss tensor(0.0215, grad_fn=<MseLossBackward>)

Loss tensor(0.0214, grad_fn=<MseLossBackward>)

Loss tensor(0.0214, grad_fn=<MseLossBackward>)

Loss tensor(0.0213, grad_fn=<MseLossBack

Loss tensor(0.0149, grad_fn=<MseLossBackward>)

Loss tensor(0.0149, grad_fn=<MseLossBackward>)

Loss tensor(0.0149, grad_fn=<MseLossBackward>)

Loss tensor(0.0148, grad_fn=<MseLossBackward>)

Loss tensor(0.0148, grad_fn=<MseLossBackward>)

Loss tensor(0.0148, grad_fn=<MseLossBackward>)

Loss tensor(0.0147, grad_fn=<MseLossBackward>)

Loss tensor(0.0147, grad_fn=<MseLossBackward>)

Loss tensor(0.0147, grad_fn=<MseLossBackward>)

Loss tensor(0.0146, grad_fn=<MseLossBackward>)

Loss tensor(0.0146, grad_fn=<MseLossBackward>)

Loss tensor(0.0146, grad_fn=<MseLossBackward>)

Loss tensor(0.0146, grad_fn=<MseLossBackward>)

Loss tensor(0.0145, grad_fn=<MseLossBackward>)

Loss tensor(0.0145, grad_fn=<MseLossBackward>)

Loss tensor(0.0145, grad_fn=<MseLossBackward>)

Loss tensor(0.0144, grad_fn=<MseLossBackward>)

Loss tensor(0.0144, grad_fn=<MseLossBackward>)

Loss tensor(0.0144, grad_fn=<MseLossBackward>)

Loss tensor(0.0143, grad_fn=<MseLossBackward>)

Loss tensor(0.0143, grad_fn=<MseLossBack

In [13]:
net.fc2.weight

Parameter containing:
tensor([[-1.1487, -2.8900, -2.2199, -1.5740,  4.4850, -1.9831,  0.3055,  1.4705,
         -3.6058, -0.3897]], requires_grad=True)

In [14]:
net.fc1.weight

Parameter containing:
tensor([[-1.1026],
        [-2.4856],
        [-2.0150],
        [-0.9944],
        [ 3.5228],
        [-1.6769],
        [-0.0651],
        [ 1.3150],
        [-1.3941],
        [-0.5549]], requires_grad=True)

In [15]:
waht=torch.from_numpy(np.array([[1000.0]]))
waht=waht.type('torch.FloatTensor')
net(waht)

tensor([[17742.5449]], grad_fn=<AddmmBackward>)